$bsStyle = @{
    Reset      = $PSStyle.Reset
    ForeGround = [ordered] @{
        White  = [ordered] @{ 
            Bright      = $PSStyle.Foreground.BrightWhite
            White       = $PSStyle.Foreground.White
            Ivory       = $PSStyle.Foreground.FromRgb(255, 255, 240)
            EggShell    = $PSStyle.Foreground.FromRgb(240, 234, 214)

            AntiFlash   = $PSStyle.Foreground.FromRgb(242, 243, 244)
            Antique     = $PSStyle.Foreground.FromRgb(250, 235, 215)
            Ghost       = $PSStyle.Foreground.FromRgb(248, 248, 255)
            Smoke       = $PSStyle.Foreground.FromRgb(245, 245, 245)
            Dutch       = $PSStyle.Foreground.FromRgb(239, 223, 187)

            OldLace     = $PSStyle.Foreground.FromRgb(253, 245, 230)
            FloralWhite = $PSStyle.Foreground.FromRgb(255, 250, 240)
            Linen       = $PSStyle.Foreground.FromRgb(250, 240, 230)

        }
        Black  = [ordered] @{
            Black  = $PSStyle.Foreground.FromRgb(0, 0, 0)
            Smokey = $PSStyle.Foreground.FromRgb(26, 0, 0)
            Coral  = $PSStyle.Foreground.FromRgb(84, 98, 111)
        }

        Gray   = [ordered] @{
            Gainsboro      = $PSStyle.Foreground.FromRgb(220, 220, 220)
            LightGray      = $PSStyle.Foreground.FromRgb(211, 211, 211)
            Silver         = $PSStyle.Foreground.FromRgb(192, 192, 192)
            DarkGray       = $PSStyle.Foreground.FromRgb(169, 169, 169)
            Gray           = $PSStyle.Foreground.FromRgb(128, 128, 128)
            DimGray        = $PSStyle.Foreground.FromRgb(105, 105, 105)
            LightSlateGray = $PSStyle.Foreground.FromRgb(119, 136, 153)
            SlateGray      = $PSStyle.Foreground.FromRgb(112, 128, 144)
            DarkSlateGray  = $PSStyle.Foreground.FromRgb(47, 79, 79)
        }

        Brown  = [ordered] @{
            Bean = $PSStyle.Foreground.FromRgb(61, 12, 2)
        }

        Pink   = [ordered] @{
            LavenderBlush = $PSStyle.Foreground.FromRgb(255, 240, 245)
            ClassicRose   = $PSStyle.Foreground.FromRgb(251, 204, 231)
            PastelMagenta = $PSStyle.Foreground.FromRgb(244, 154, 194)
            SkyMagenta    = $PSStyle.Foreground.FromRgb(207, 113, 175)
            BrightPink    = $PSStyle.Foreground.FromRgb(255, 0, 127)
            DarkRaspberry = $PSStyle.Foreground.FromRgb(135, 38, 87)
            Eggplant      = $PSStyle.Foreground.FromRgb(97, 64, 81)
            Pastel        = $PSStyle.Foreground.FromRgb(255, 209, 220)
            Pink          = $PSStyle.Foreground.FromRgb(255, 192, 203)
            CherryBlossom = $PSStyle.Foreground.FromRgb(255, 183, 197)
            Flamingo      = $PSStyle.Foreground.FromRgb(252, 142, 172)
            Dark          = $PSStyle.Foreground.FromRgb(231, 84, 128)
            Blush         = $PSStyle.Foreground.FromRgb(222, 93, 131)
            Cherry        = $PSStyle.Foreground.FromRgb(222, 49, 99)
            Raspberry     = $PSStyle.Foreground.FromRgb(227, 11, 93)
            Ruby          = $PSStyle.Foreground.FromRgb(224, 17, 95)
            BrightMaroon  = $PSStyle.Foreground.FromRgb(195, 33, 72)
            Burgundy      = $PSStyle.Foreground.FromRgb(128, 0, 32)
            DarkScarlet   = $PSStyle.Foreground.FromRgb(86, 3, 25)
        }

        Red    = [ordered] @{
            BubbleGum        = $PSStyle.Foreground.FromRgb(255, 193, 204)
            Amaranth         = $PSStyle.Foreground.FromRgb(229, 43, 80)
            DarkTerraCotta   = $PSStyle.Foreground.FromRgb(204, 78, 92)
            Bazaar           = $PSStyle.Foreground.FromRgb(152, 119, 123)
            Alizarin         = $PSStyle.Foreground.FromRgb(227, 38, 54)
            Crimson          = $PSStyle.Foreground.FromRgb(220, 20, 60)
            Cadmium          = $PSStyle.Foreground.FromRgb(227, 0, 34)
            Cardinal         = $PSStyle.Foreground.FromRgb(196, 30, 58)
            Cordovan         = $PSStyle.Foreground.FromRgb(137, 63, 69)
            Carmine          = $PSStyle.Foreground.FromRgb(150, 0, 24)
            Rosewood         = $PSStyle.Foreground.FromRgb(101, 0, 11)
            Snow             = $PSStyle.Foreground.FromRgb(255, 250, 250)
            BabyPink         = $PSStyle.Foreground.FromRgb(244, 194, 194)
            Pastel           = $PSStyle.Foreground.FromRgb(255, 105, 97)
            IndianRed        = $PSStyle.Foreground.FromRgb(255, 92, 92)
            FerrariRed       = $PSStyle.Foreground.FromRgb(255, 28, 0)
            CandyApple       = $PSStyle.Foreground.FromRgb(255, 8, 0)
            Red              = $PSStyle.Foreground.FromRgb(255, 0, 0)
            Chestnut         = $PSStyle.Foreground.FromRgb(205, 92, 92)
            Cinnabar         = $PSStyle.Foreground.FromRgb(227, 66, 52)
            Jasper           = $PSStyle.Foreground.FromRgb(215, 59, 62)
            FireEngine       = $PSStyle.Foreground.FromRgb(206, 22, 32)
            BostonUniversity = $PSStyle.Foreground.FromRgb(204, 0, 0)
            Firebrick        = $PSStyle.Foreground.FromRgb(178, 34, 34)
            Cornell          = $PSStyle.Foreground.FromRgb(179, 27, 27)
            DarkCandyApple   = $PSStyle.Foreground.FromRgb(164, 0, 0)
            Maroon           = $PSStyle.Foreground.FromRgb(128, 0, 0)
            Prune            = $PSStyle.Foreground.FromRgb(112, 28, 28)
            DarkSienna       = $PSStyle.Foreground.FromRgb(60, 20, 20)
            SealBrown        = $PSStyle.Foreground.FromRgb(50, 20, 20)
        }

        Red1   = [ordered] @{
            AlabamaCrimson   = $PSStyle.Foreground.FromRgb(175, 0, 42)
            MistyRose        = $PSStyle.Foreground.FromRgb(255, 230, 230)
            BubbleGum        = $PSStyle.Foreground.FromRgb(255, 204, 204)
            Melon            = $PSStyle.Foreground.FromRgb(255, 179, 179)
            LightSalmonPink  = $PSStyle.Foreground.FromRgb(255, 153, 153)
            CoralPink        = $PSStyle.Foreground.FromRgb(255, 128, 128)
            Pastel           = $PSStyle.Foreground.FromRgb(255, 102, 102)
            CoralRed         = $PSStyle.Foreground.FromRgb(255, 77, 77)
            DeepCarminePink  = $PSStyle.Foreground.FromRgb(255, 51, 51)
            RedRYB           = $PSStyle.Foreground.FromRgb(255, 25, 25)
            Red              = $PSStyle.Foreground.FromRgb(255, 0, 0)
            KUCrimson        = $PSStyle.Foreground.FromRgb(230, 0, 0)
            BostonUniversity = $PSStyle.Foreground.FromRgb(204, 0, 0)
            Mordant          = $PSStyle.Foreground.FromRgb(179, 0, 0)
            OUCrimson        = $PSStyle.Foreground.FromRgb(153, 0, 0)
            Maroon           = $PSStyle.Foreground.FromRgb(128, 0, 0)
            Rosewood         = $PSStyle.Foreground.FromRgb(102, 0, 0)
            Bulgarian        = $PSStyle.Foreground.FromRgb(77, 0, 0)
            BulgarianRose    = $PSStyle.Foreground.FromRgb(51, 0, 0)
        }

        Orange = [ordered] @{
            AtomicTangerine = $PSStyle.Foreground.FromRgb(255, 153, 102)
            Salmon          = $PSStyle.Foreground.FromRgb(255, 140, 105)
            DarkSalmon      = $PSStyle.Foreground.FromRgb(233, 150, 122)
            Coral           = $PSStyle.Foreground.FromRgb(255, 127, 80)
            BurntSienna     = $PSStyle.Foreground.FromRgb(233, 116, 81)
            Portland        = $PSStyle.Foreground.FromRgb(255, 90, 54)
            TerraCotta      = $PSStyle.Foreground.FromRgb(226, 114, 91)
            Coquelicot      = $PSStyle.Foreground.FromRgb(255, 56, 0)
            Flame           = $PSStyle.Foreground.FromRgb(226, 88, 34)
            Cinereous       = $PSStyle.Foreground.FromRgb(152, 129, 123)
            DarkCoral       = $PSStyle.Foreground.FromRgb(205, 91, 69)
            DarkChestnut    = $PSStyle.Foreground.FromRgb(152, 105, 96)
            Sinopia         = $PSStyle.Foreground.FromRgb(203, 65, 11)
            DarkPastelRed   = $PSStyle.Foreground.FromRgb(194, 59, 34)
            Mahogany        = $PSStyle.Foreground.FromRgb(192, 64, 0)
            Rust            = $PSStyle.Foreground.FromRgb(183, 65, 14)
            Bole            = $PSStyle.Foreground.FromRgb(121, 68, 59)
            BurntUmber      = $PSStyle.Foreground.FromRgb(138, 51, 36)
            Auburn          = $PSStyle.Foreground.FromRgb(109, 53, 26)
            Seashell        = $PSStyle.Foreground.FromRgb(255, 245, 238)
            Champagne       = $PSStyle.Foreground.FromRgb(247, 231, 206)
            Peach           = $PSStyle.Foreground.FromRgb(255, 229, 180)
            Wheat           = $PSStyle.Foreground.FromRgb(245, 222, 179)
            Sunset          = $PSStyle.Foreground.FromRgb(250, 214, 165)
            Apricot         = $PSStyle.Foreground.FromRgb(251, 206, 177)
            DesertSand      = $PSStyle.Foreground.FromRgb(237, 201, 175)
            PastelOrange    = $PSStyle.Foreground.FromRgb(255, 179, 71)
            Burlywood       = $PSStyle.Foreground.FromRgb(222, 184, 135)
            DarkTangerine   = $PSStyle.Foreground.FromRgb(255, 168, 18)
            ChromeYellow    = $PSStyle.Foreground.FromRgb(255, 167, 0)
            Fawn            = $PSStyle.Foreground.FromRgb(229, 170, 112)
            EarthYellow     = $PSStyle.Foreground.FromRgb(225, 169, 95)
            IndianYellow    = $PSStyle.Foreground.FromRgb(227, 168, 87)
            Khaki           = $PSStyle.Foreground.FromRgb(195, 176, 145)
            DarkOrange      = $PSStyle.Foreground.FromRgb(255, 140, 0)
            Gamboge         = $PSStyle.Foreground.FromRgb(228, 155, 15)
            CarrotOrange    = $PSStyle.Foreground.FromRgb(237, 145, 33)
            Orange          = $PSStyle.Foreground.FromRgb(255, 127, 0)
            Tangerine       = $PSStyle.Foreground.FromRgb(242, 133, 0)
            CadmiumOrange   = $PSStyle.Foreground.FromRgb(237, 135, 45)
            Pumpkin         = $PSStyle.Foreground.FromRgb(255, 117, 24)
            Desert          = $PSStyle.Foreground.FromRgb(193, 154, 107)
            SafetyOrange    = $PSStyle.Foreground.FromRgb(255, 103, 0)
            Bronze          = $PSStyle.Foreground.FromRgb(205, 127, 50)
            Ochre           = $PSStyle.Foreground.FromRgb(204, 119, 34)
            Cinnamon        = $PSStyle.Foreground.FromRgb(210, 105, 30)
            Copper          = $PSStyle.Foreground.FromRgb(184, 115, 51)
            Chamoisee       = $PSStyle.Foreground.FromRgb(160, 120, 90)
            BurntOrange     = $PSStyle.Foreground.FromRgb(204, 85, 0)
            Shadow          = $PSStyle.Foreground.FromRgb(138, 121, 93)
            GoldenBrown     = $PSStyle.Foreground.FromRgb(153, 101, 21)
            PastelBrown     = $PSStyle.Foreground.FromRgb(131, 105, 83)
            RawUmber        = $PSStyle.Foreground.FromRgb(130, 102, 68)
            Brown           = $PSStyle.Foreground.FromRgb(150, 75, 0)
            Chocolate       = $PSStyle.Foreground.FromRgb(123, 63, 0)
            Sepia           = $PSStyle.Foreground.FromRgb(112, 66, 20)
            DarkBrown       = $PSStyle.Foreground.FromRgb(101, 67, 33)
            DarkLava        = $PSStyle.Foreground.FromRgb(72, 60, 50)
            Bistre          = $PSStyle.Foreground.FromRgb(61, 43, 31)
        }

        Yellow = [ordered] @{
            Cornsilk       = $PSStyle.Foreground.FromRgb(255, 248, 220)
            Blond          = $PSStyle.Foreground.FromRgb(250, 240, 190)
            Pearl          = $PSStyle.Foreground.FromRgb(240, 234, 214)
            Platinum       = $PSStyle.Foreground.FromRgb(229, 228, 226)
            Vanilla        = $PSStyle.Foreground.FromRgb(243, 229, 171)
            Mustard        = $PSStyle.Foreground.FromRgb(255, 219, 88)
            Buff           = $PSStyle.Foreground.FromRgb(240, 220, 130)
            BananaYellow   = $PSStyle.Foreground.FromRgb(255, 209, 42)
            ArylideYellow  = $PSStyle.Foreground.FromRgb(233, 214, 107)
            Saffron        = $PSStyle.Foreground.FromRgb(244, 196, 48)
            Amber          = $PSStyle.Foreground.FromRgb(255, 191, 0)
            Sand           = $PSStyle.Foreground.FromRgb(194, 178, 128)
            Goldenrod      = $PSStyle.Foreground.FromRgb(218, 165, 32)
            DarkGoldenrod  = $PSStyle.Foreground.FromRgb(184, 134, 11)
            DarkTan        = $PSStyle.Foreground.FromRgb(145, 129, 81)
            SandDune       = $PSStyle.Foreground.FromRgb(150, 113, 23)
            Ivory          = $PSStyle.Foreground.FromRgb(255, 255, 240)
            Cream          = $PSStyle.Foreground.FromRgb(255, 253, 208)
            PastelYellow   = $PSStyle.Foreground.FromRgb(253, 253, 150)
            Beige          = $PSStyle.Foreground.FromRgb(245, 245, 220)
            Daffodil       = $PSStyle.Foreground.FromRgb(255, 255, 49)
            Yellow         = $PSStyle.Foreground.FromRgb(255, 255, 0)
            Icterine       = $PSStyle.Foreground.FromRgb(252, 247, 94)
            Lemon          = $PSStyle.Foreground.FromRgb(255, 247, 0)
            CanaryYellow   = $PSStyle.Foreground.FromRgb(255, 239, 0)
            Flavescent     = $PSStyle.Foreground.FromRgb(247, 233, 142)
            Corn           = $PSStyle.Foreground.FromRgb(251, 236, 93)
            GoldenYellow   = $PSStyle.Foreground.FromRgb(255, 223, 0)
            TitaniumYellow = $PSStyle.Foreground.FromRgb(238, 230, 0)
            Dandelion      = $PSStyle.Foreground.FromRgb(240, 225, 48)
            Peridot        = $PSStyle.Foreground.FromRgb(230, 226, 0)
            Straw          = $PSStyle.Foreground.FromRgb(228, 217, 111)
            Sandstorm      = $PSStyle.Foreground.FromRgb(236, 213, 64)
            PastelGray     = $PSStyle.Foreground.FromRgb(207, 207, 196)
            Citrine        = $PSStyle.Foreground.FromRgb(228, 208, 10)
            DarkKhaki      = $PSStyle.Foreground.FromRgb(189, 183, 107)
            Brass          = $PSStyle.Foreground.FromRgb(181, 166, 66)
        }

        Green  = [ordered] @{
            Chartreuse         = $PSStyle.Foreground.FromRgb(223, 255, 0)
            Lime               = $PSStyle.Foreground.FromRgb(191, 255, 0)
            SpringBud          = $PSStyle.Foreground.FromRgb(167, 252, 0)
            Pear               = $PSStyle.Foreground.FromRgb(209, 226, 49)
            AndroidGreen       = $PSStyle.Foreground.FromRgb(164, 198, 57)
            AppleGreen         = $PSStyle.Foreground.FromRgb(141, 182, 0)
            BattleshipGrey     = $PSStyle.Foreground.FromRgb(132, 132, 130)
            Olive              = $PSStyle.Foreground.FromRgb(128, 128, 0)
            ArmyGreen          = $PSStyle.Foreground.FromRgb(75, 83, 32)
            Inchworm           = $PSStyle.Foreground.FromRgb(178, 236, 93)
            LawnGreen          = $PSStyle.Foreground.FromRgb(124, 252, 0)
            BrightGreen        = $PSStyle.Foreground.FromRgb(102, 255, 0)
            Celadon            = $PSStyle.Foreground.FromRgb(172, 225, 175)
            PastelGreen        = $PSStyle.Foreground.FromRgb(119, 221, 119)
            Pistachio          = $PSStyle.Foreground.FromRgb(147, 197, 114)
            DollarBill         = $PSStyle.Foreground.FromRgb(133, 187, 101)
            Asparagus          = $PSStyle.Foreground.FromRgb(135, 169, 107)
            DarkPastelGreen    = $PSStyle.Foreground.FromRgb(3, 192, 60)
            CamouflageGreen    = $PSStyle.Foreground.FromRgb(120, 134, 107)
            IndiaGreen         = $PSStyle.Foreground.FromRgb(19, 136, 8)
            Green              = $PSStyle.Foreground.FromRgb(0, 128, 0)
            DarkOliveGreen     = $PSStyle.Foreground.FromRgb(85, 107, 47)
            RifleGreen         = $PSStyle.Foreground.FromRgb(65, 72, 51)
            Aquamarine         = $PSStyle.Foreground.FromRgb(127, 255, 212)
            Clover             = $PSStyle.Foreground.FromRgb(0, 255, 111)
            AshGrey            = $PSStyle.Foreground.FromRgb(178, 190, 181)
            CambridgeBlue      = $PSStyle.Foreground.FromRgb(163, 193, 173)
            CaribbeanGreen     = $PSStyle.Foreground.FromRgb(0, 204, 153)
            Emerald            = $PSStyle.Foreground.FromRgb(80, 200, 120)
            Mint               = $PSStyle.Foreground.FromRgb(62, 180, 137)
            Jade               = $PSStyle.Foreground.FromRgb(0, 168, 107)
            Xanadu             = $PSStyle.Foreground.FromRgb(115, 134, 120)
            TropicalRainForest = $PSStyle.Foreground.FromRgb(0, 117, 94)
            DarkSpringGreen    = $PSStyle.Foreground.FromRgb(23, 114, 69)
            CadmiumGreen       = $PSStyle.Foreground.FromRgb(0, 107, 60)
            ForestGreen        = $PSStyle.Foreground.FromRgb(1, 68, 33)
            BritishRacingGreen = $PSStyle.Foreground.FromRgb(0, 66, 37)
            DarkGreen          = $PSStyle.Foreground.FromRgb(1, 50, 32)
            DarkJungleGreen    = $PSStyle.Foreground.FromRgb(26, 36, 33)
        }

        Cyan   = [ordered] @{
            Bubbles         = $PSStyle.Foreground.FromRgb(231, 254, 255)
            Cyan            = $PSStyle.Foreground.FromRgb(0, 255, 255)
            ColumbiaBlue    = $PSStyle.Foreground.FromRgb(155, 221, 255)
            BrightTurquoise = $PSStyle.Foreground.FromRgb(8, 232, 222)
            BabyBlue        = $PSStyle.Foreground.FromRgb(137, 207, 240)
            SkyBlue         = $PSStyle.Foreground.FromRgb(135, 206, 235)
            PastelBlue      = $PSStyle.Foreground.FromRgb(174, 198, 207)
            Turquoise       = $PSStyle.Foreground.FromRgb(48, 213, 200)
            DarkCyan        = $PSStyle.Foreground.FromRgb(0, 139, 139)
            Cerulean        = $PSStyle.Foreground.FromRgb(0, 123, 167)
            Teal            = $PSStyle.Foreground.FromRgb(0, 128, 128)
            PineGreen       = $PSStyle.Foreground.FromRgb(1, 121, 111)
            DarkSlateGray   = $PSStyle.Foreground.FromRgb(47, 79, 79)
        }

        Blue   = [ordered] @{
            AliceBlue              = $PSStyle.Foreground.FromRgb(240, 248, 255)
            BabyBlueEyes           = $PSStyle.Foreground.FromRgb(161, 202, 241)
            CarolinaBlue           = $PSStyle.Foreground.FromRgb(153, 186, 221)
            Iceberg                = $PSStyle.Foreground.FromRgb(113, 166, 210)
            CornflowerBlue         = $PSStyle.Foreground.FromRgb(100, 149, 237)
            DarkPastelBlue         = $PSStyle.Foreground.FromRgb(119, 158, 203)
            UnitedNationsBlue      = $PSStyle.Foreground.FromRgb(91, 146, 229)
            BleuDeFrance           = $PSStyle.Foreground.FromRgb(49, 140, 231)
            Azure                  = $PSStyle.Foreground.FromRgb(0, 127, 255)
            AirForceBlue           = $PSStyle.Foreground.FromRgb(93, 138, 168)
            Glaucous               = $PSStyle.Foreground.FromRgb(96, 130, 182)
            SteelBlue              = $PSStyle.Foreground.FromRgb(70, 130, 180)
            Denim                  = $PSStyle.Foreground.FromRgb(21, 96, 189)
            Cadet                  = $PSStyle.Foreground.FromRgb(83, 104, 120)
            Cobalt                 = $PSStyle.Foreground.FromRgb(0, 71, 171)
            YaleBlue               = $PSStyle.Foreground.FromRgb(15, 77, 146)
            DarkCerulean           = $PSStyle.Foreground.FromRgb(8, 69, 126)
            Charcoal               = $PSStyle.Foreground.FromRgb(54, 69, 79)
            Arsenic                = $PSStyle.Foreground.FromRgb(59, 68, 75)
            DarkMidnightBlue       = $PSStyle.Foreground.FromRgb(0, 51, 102)
            CoolBlack              = $PSStyle.Foreground.FromRgb(0, 46, 99)
            OxfordBlue             = $PSStyle.Foreground.FromRgb(0, 33, 71)
            GhostWhite             = $PSStyle.Foreground.FromRgb(248, 248, 255)
            LavenderBlue           = $PSStyle.Foreground.FromRgb(204, 204, 255)
            LavenderGray           = $PSStyle.Foreground.FromRgb(196, 195, 208)
            Ceil                   = $PSStyle.Foreground.FromRgb(146, 161, 207)
            CoolGrey               = $PSStyle.Foreground.FromRgb(140, 146, 172)
            Blue                   = $PSStyle.Foreground.FromRgb(0, 0, 255)
            CeruleanBlue           = $PSStyle.Foreground.FromRgb(42, 82, 190)
            InternationalKleinBlue = $PSStyle.Foreground.FromRgb(0, 47, 167)
            DarkPowderBlue         = $PSStyle.Foreground.FromRgb(0, 51, 153)
            DukeBlue               = $PSStyle.Foreground.FromRgb(0, 0, 156)
            Ultramarine            = $PSStyle.Foreground.FromRgb(18, 10, 143)
            DarkBlue               = $PSStyle.Foreground.FromRgb(0, 0, 139)
            NavyBlue               = $PSStyle.Foreground.FromRgb(0, 0, 128)
            MidnightBlue           = $PSStyle.Foreground.FromRgb(25, 25, 112)
            Sapphire               = $PSStyle.Foreground.FromRgb(8, 37, 103)
            RoyalBlue              = $PSStyle.Foreground.FromRgb(0, 35, 102)
        }

        Purple = [ordered] @{
            BrightLavender   = $PSStyle.Foreground.FromRgb(191, 148, 228)
            Lavender         = $PSStyle.Foreground.FromRgb(181, 126, 220)
            DarkPastelPurple = $PSStyle.Foreground.FromRgb(150, 111, 214)
            Violet           = $PSStyle.Foreground.FromRgb(143, 0, 255)
            DarkLavender     = $PSStyle.Foreground.FromRgb(115, 79, 150)
            PurpleHeart      = $PSStyle.Foreground.FromRgb(105, 53, 156)
            BrightUbe        = $PSStyle.Foreground.FromRgb(209, 159, 232)
            Magenta          = $PSStyle.Foreground.FromRgb(255, 0, 255)
            PastelViolet     = $PSStyle.Foreground.FromRgb(203, 153, 201)
            PastelPurple     = $PSStyle.Foreground.FromRgb(179, 158, 181)
            Byzantine        = $PSStyle.Foreground.FromRgb(189, 51, 164)
            DarkViolet       = $PSStyle.Foreground.FromRgb(148, 0, 211)
            Plum             = $PSStyle.Foreground.FromRgb(142, 69, 133)
            DarkMagenta      = $PSStyle.Foreground.FromRgb(139, 0, 139)
            Byzantium        = $PSStyle.Foreground.FromRgb(112, 41, 99)
            DarkByzantium    = $PSStyle.Foreground.FromRgb(93, 57, 84)
        }
    }
    BackGround = [ordered] @{
        White  = [ordered] @{ 
            Bright      = $PSStyle.BackGround.BrightWhite
            White       = $PSStyle.BackGround.White
            Ivory       = $PSStyle.BackGround.FromRgb(255, 255, 240)
            EggShell    = $PSStyle.BackGround.FromRgb(240, 234, 214)

            AntiFlash   = $PSStyle.BackGround.FromRgb(242, 243, 244)
            Antique     = $PSStyle.BackGround.FromRgb(250, 235, 215)
            Ghost       = $PSStyle.BackGround.FromRgb(248, 248, 255)
            Smoke       = $PSStyle.BackGround.FromRgb(245, 245, 245)
            Dutch       = $PSStyle.BackGround.FromRgb(239, 223, 187)

            OldLace     = $PSStyle.BackGround.FromRgb(253, 245, 230)
            FloralWhite = $PSStyle.BackGround.FromRgb(255, 250, 240)
            Linen       = $PSStyle.BackGround.FromRgb(250, 240, 230)
        }
        Black  = [ordered] @{
            Black  = $PSStyle.BackGround.FromRgb(0, 0, 0)
            Smokey = $PSStyle.BackGround.FromRgb(26, 0, 0)
            Coral  = $PSStyle.BackGround.FromRgb(84, 98, 111)
        }
        Brown  = [ordered] @{
            Bean = $PSStyle.BackGround.FromRgb(61, 12, 2)
        }

        Pink   = [ordered] @{
            LavenderBlush = $PSStyle.BackGround.FromRgb(255, 240, 245)
            ClassicRose   = $PSStyle.BackGround.FromRgb(251, 204, 231)
            PastelMagenta = $PSStyle.BackGround.FromRgb(244, 154, 194)
            SkyMagenta    = $PSStyle.BackGround.FromRgb(207, 113, 175)
            BrightPink    = $PSStyle.BackGround.FromRgb(255, 0, 127)
            DarkRaspberry = $PSStyle.BackGround.FromRgb(135, 38, 87)
            Eggplant      = $PSStyle.BackGround.FromRgb(97, 64, 81)
            Pastel        = $PSStyle.BackGround.FromRgb(255, 209, 220)
            Pink          = $PSStyle.BackGround.FromRgb(255, 192, 203)
            CherryBlossom = $PSStyle.BackGround.FromRgb(255, 183, 197)
            Flamingo      = $PSStyle.BackGround.FromRgb(252, 142, 172)
            Dark          = $PSStyle.BackGround.FromRgb(231, 84, 128)
            Blush         = $PSStyle.BackGround.FromRgb(222, 93, 131)
            Cherry        = $PSStyle.BackGround.FromRgb(222, 49, 99)
            Raspberry     = $PSStyle.BackGround.FromRgb(227, 11, 93)
            Ruby          = $PSStyle.BackGround.FromRgb(224, 17, 95)
            BrightMaroon  = $PSStyle.BackGround.FromRgb(195, 33, 72)
            Burgundy      = $PSStyle.BackGround.FromRgb(128, 0, 32)
            DarkScarlet   = $PSStyle.BackGround.FromRgb(86, 3, 25)
        }

        Red    = [ordered] @{
            BubbleGum        = $PSStyle.BackGround.FromRgb(255, 193, 204)
            Amaranth         = $PSStyle.BackGround.FromRgb(229, 43, 80)
            DarkTerraCotta   = $PSStyle.BackGround.FromRgb(204, 78, 92)
            Bazaar           = $PSStyle.BackGround.FromRgb(152, 119, 123)
            Alizarin         = $PSStyle.BackGround.FromRgb(227, 38, 54)
            Crimson          = $PSStyle.BackGround.FromRgb(220, 20, 60)
            Cadmium          = $PSStyle.BackGround.FromRgb(227, 0, 34)
            Cardinal         = $PSStyle.BackGround.FromRgb(196, 30, 58)
            Cordovan         = $PSStyle.BackGround.FromRgb(137, 63, 69)
            Carmine          = $PSStyle.BackGround.FromRgb(150, 0, 24)
            Rosewood         = $PSStyle.BackGround.FromRgb(101, 0, 11)
            Snow             = $PSStyle.BackGround.FromRgb(255, 250, 250)
            BabyPink         = $PSStyle.BackGround.FromRgb(244, 194, 194)
            Pastel           = $PSStyle.BackGround.FromRgb(255, 105, 97)
            IndianRed        = $PSStyle.BackGround.FromRgb(255, 92, 92)
            FerrariRed       = $PSStyle.BackGround.FromRgb(255, 28, 0)
            CandyApple       = $PSStyle.BackGround.FromRgb(255, 8, 0)
            Red              = $PSStyle.BackGround.FromRgb(255, 0, 0)
            Chestnut         = $PSStyle.BackGround.FromRgb(205, 92, 92)
            Cinnabar         = $PSStyle.BackGround.FromRgb(227, 66, 52)
            Jasper           = $PSStyle.BackGround.FromRgb(215, 59, 62)
            FireEngine       = $PSStyle.BackGround.FromRgb(206, 22, 32)
            BostonUniversity = $PSStyle.BackGround.FromRgb(204, 0, 0)
            Firebrick        = $PSStyle.BackGround.FromRgb(178, 34, 34)
            Cornell          = $PSStyle.BackGround.FromRgb(179, 27, 27)
            DarkCandyApple   = $PSStyle.BackGround.FromRgb(164, 0, 0)
            Maroon           = $PSStyle.BackGround.FromRgb(128, 0, 0)
            Prune            = $PSStyle.BackGround.FromRgb(112, 28, 28)
            DarkSienna       = $PSStyle.BackGround.FromRgb(60, 20, 20)
            SealBrown        = $PSStyle.BackGround.FromRgb(50, 20, 20)
        }

        Red1   = [ordered] @{
            AlabamaCrimson   = $PSStyle.BackGround.FromRgb(175, 0, 42)
            MistyRose        = $PSStyle.BackGround.FromRgb(255, 230, 230)
            BubbleGum        = $PSStyle.BackGround.FromRgb(255, 204, 204)
            Melon            = $PSStyle.BackGround.FromRgb(255, 179, 179)
            LightSalmonPink  = $PSStyle.BackGround.FromRgb(255, 153, 153)
            CoralPink        = $PSStyle.BackGround.FromRgb(255, 128, 128)
            Pastel           = $PSStyle.BackGround.FromRgb(255, 102, 102)
            CoralRed         = $PSStyle.BackGround.FromRgb(255, 77, 77)
            DeepCarminePink  = $PSStyle.BackGround.FromRgb(255, 51, 51)
            RedRYB           = $PSStyle.BackGround.FromRgb(255, 25, 25)
            Red              = $PSStyle.BackGround.FromRgb(255, 0, 0)
            KUCrimson        = $PSStyle.BackGround.FromRgb(230, 0, 0)
            BostonUniversity = $PSStyle.BackGround.FromRgb(204, 0, 0)
            Mordant          = $PSStyle.BackGround.FromRgb(179, 0, 0)
            OUCrimson        = $PSStyle.BackGround.FromRgb(153, 0, 0)
            Maroon           = $PSStyle.BackGround.FromRgb(128, 0, 0)
            Rosewood         = $PSStyle.BackGround.FromRgb(102, 0, 0)
            Bulgarian        = $PSStyle.BackGround.FromRgb(77, 0, 0)
            BulgarianRose    = $PSStyle.BackGround.FromRgb(51, 0, 0)
        }

        Orange = [ordered] @{
            AtomicTangerine = $PSStyle.BackGround.FromRgb(255, 153, 102)
            Salmon          = $PSStyle.BackGround.FromRgb(255, 140, 105)
            DarkSalmon      = $PSStyle.BackGround.FromRgb(233, 150, 122)
            Coral           = $PSStyle.BackGround.FromRgb(255, 127, 80)
            BurntSienna     = $PSStyle.BackGround.FromRgb(233, 116, 81)
            Portland        = $PSStyle.BackGround.FromRgb(255, 90, 54)
            TerraCotta      = $PSStyle.BackGround.FromRgb(226, 114, 91)
            Coquelicot      = $PSStyle.BackGround.FromRgb(255, 56, 0)
            Flame           = $PSStyle.BackGround.FromRgb(226, 88, 34)
            Cinereous       = $PSStyle.BackGround.FromRgb(152, 129, 123)
            DarkCoral       = $PSStyle.BackGround.FromRgb(205, 91, 69)
            DarkChestnut    = $PSStyle.BackGround.FromRgb(152, 105, 96)
            Sinopia         = $PSStyle.BackGround.FromRgb(203, 65, 11)
            DarkPastelRed   = $PSStyle.BackGround.FromRgb(194, 59, 34)
            Mahogany        = $PSStyle.BackGround.FromRgb(192, 64, 0)
            Rust            = $PSStyle.BackGround.FromRgb(183, 65, 14)
            Bole            = $PSStyle.BackGround.FromRgb(121, 68, 59)
            BurntUmber      = $PSStyle.BackGround.FromRgb(138, 51, 36)
            Auburn          = $PSStyle.BackGround.FromRgb(109, 53, 26)
            Seashell        = $PSStyle.BackGround.FromRgb(255, 245, 238)
            Champagne       = $PSStyle.BackGround.FromRgb(247, 231, 206)
            Peach           = $PSStyle.BackGround.FromRgb(255, 229, 180)
            Wheat           = $PSStyle.BackGround.FromRgb(245, 222, 179)
            Sunset          = $PSStyle.BackGround.FromRgb(250, 214, 165)
            Apricot         = $PSStyle.BackGround.FromRgb(251, 206, 177)
            DesertSand      = $PSStyle.BackGround.FromRgb(237, 201, 175)
            PastelOrange    = $PSStyle.BackGround.FromRgb(255, 179, 71)
            Burlywood       = $PSStyle.BackGround.FromRgb(222, 184, 135)
            DarkTangerine   = $PSStyle.BackGround.FromRgb(255, 168, 18)
            ChromeYellow    = $PSStyle.BackGround.FromRgb(255, 167, 0)
            Fawn            = $PSStyle.BackGround.FromRgb(229, 170, 112)
            EarthYellow     = $PSStyle.BackGround.FromRgb(225, 169, 95)
            IndianYellow    = $PSStyle.BackGround.FromRgb(227, 168, 87)
            Khaki           = $PSStyle.BackGround.FromRgb(195, 176, 145)
            DarkOrange      = $PSStyle.BackGround.FromRgb(255, 140, 0)
            Gamboge         = $PSStyle.BackGround.FromRgb(228, 155, 15)
            CarrotOrange    = $PSStyle.BackGround.FromRgb(237, 145, 33)
            Orange          = $PSStyle.BackGround.FromRgb(255, 127, 0)
            Tangerine       = $PSStyle.BackGround.FromRgb(242, 133, 0)
            CadmiumOrange   = $PSStyle.BackGround.FromRgb(237, 135, 45)
            Pumpkin         = $PSStyle.BackGround.FromRgb(255, 117, 24)
            Desert          = $PSStyle.BackGround.FromRgb(193, 154, 107)
            SafetyOrange    = $PSStyle.BackGround.FromRgb(255, 103, 0)
            Bronze          = $PSStyle.BackGround.FromRgb(205, 127, 50)
            Ochre           = $PSStyle.BackGround.FromRgb(204, 119, 34)
            Cinnamon        = $PSStyle.BackGround.FromRgb(210, 105, 30)
            Copper          = $PSStyle.BackGround.FromRgb(184, 115, 51)
            Chamoisee       = $PSStyle.BackGround.FromRgb(160, 120, 90)
            BurntOrange     = $PSStyle.BackGround.FromRgb(204, 85, 0)
            Shadow          = $PSStyle.BackGround.FromRgb(138, 121, 93)
            GoldenBrown     = $PSStyle.BackGround.FromRgb(153, 101, 21)
            PastelBrown     = $PSStyle.BackGround.FromRgb(131, 105, 83)
            RawUmber        = $PSStyle.BackGround.FromRgb(130, 102, 68)
            Brown           = $PSStyle.BackGround.FromRgb(150, 75, 0)
            Chocolate       = $PSStyle.BackGround.FromRgb(123, 63, 0)
            Sepia           = $PSStyle.BackGround.FromRgb(112, 66, 20)
            DarkBrown       = $PSStyle.BackGround.FromRgb(101, 67, 33)
            DarkLava        = $PSStyle.BackGround.FromRgb(72, 60, 50)
            Bistre          = $PSStyle.BackGround.FromRgb(61, 43, 31)
        }

        Yellow = [ordered] @{
            Cornsilk       = $PSStyle.BackGround.FromRgb(255, 248, 220)
            Blond          = $PSStyle.BackGround.FromRgb(250, 240, 190)
            Pearl          = $PSStyle.BackGround.FromRgb(240, 234, 214)
            Platinum       = $PSStyle.BackGround.FromRgb(229, 228, 226)
            Vanilla        = $PSStyle.BackGround.FromRgb(243, 229, 171)
            Mustard        = $PSStyle.BackGround.FromRgb(255, 219, 88)
            Buff           = $PSStyle.BackGround.FromRgb(240, 220, 130)
            BananaYellow   = $PSStyle.BackGround.FromRgb(255, 209, 42)
            ArylideYellow  = $PSStyle.BackGround.FromRgb(233, 214, 107)
            Saffron        = $PSStyle.BackGround.FromRgb(244, 196, 48)
            Amber          = $PSStyle.BackGround.FromRgb(255, 191, 0)
            Sand           = $PSStyle.BackGround.FromRgb(194, 178, 128)
            Goldenrod      = $PSStyle.BackGround.FromRgb(218, 165, 32)
            DarkGoldenrod  = $PSStyle.BackGround.FromRgb(184, 134, 11)
            DarkTan        = $PSStyle.BackGround.FromRgb(145, 129, 81)
            SandDune       = $PSStyle.BackGround.FromRgb(150, 113, 23)
            Ivory          = $PSStyle.BackGround.FromRgb(255, 255, 240)
            Cream          = $PSStyle.BackGround.FromRgb(255, 253, 208)
            PastelYellow   = $PSStyle.BackGround.FromRgb(253, 253, 150)
            Beige          = $PSStyle.BackGround.FromRgb(245, 245, 220)
            Daffodil       = $PSStyle.BackGround.FromRgb(255, 255, 49)
            Yellow         = $PSStyle.BackGround.FromRgb(255, 255, 0)
            Icterine       = $PSStyle.BackGround.FromRgb(252, 247, 94)
            Lemon          = $PSStyle.BackGround.FromRgb(255, 247, 0)
            CanaryYellow   = $PSStyle.BackGround.FromRgb(255, 239, 0)
            Flavescent     = $PSStyle.BackGround.FromRgb(247, 233, 142)
            Corn           = $PSStyle.BackGround.FromRgb(251, 236, 93)
            GoldenYellow   = $PSStyle.BackGround.FromRgb(255, 223, 0)
            TitaniumYellow = $PSStyle.BackGround.FromRgb(238, 230, 0)
            Dandelion      = $PSStyle.BackGround.FromRgb(240, 225, 48)
            Peridot        = $PSStyle.BackGround.FromRgb(230, 226, 0)
            Straw          = $PSStyle.BackGround.FromRgb(228, 217, 111)
            Sandstorm      = $PSStyle.BackGround.FromRgb(236, 213, 64)
            PastelGray     = $PSStyle.BackGround.FromRgb(207, 207, 196)
            Citrine        = $PSStyle.BackGround.FromRgb(228, 208, 10)
            DarkKhaki      = $PSStyle.BackGround.FromRgb(189, 183, 107)
            Brass          = $PSStyle.BackGround.FromRgb(181, 166, 66)
        }

        Green  = [ordered] @{
            Chartreuse         = $PSStyle.BackGround.FromRgb(223, 255, 0)
            Lime               = $PSStyle.BackGround.FromRgb(191, 255, 0)
            SpringBud          = $PSStyle.BackGround.FromRgb(167, 252, 0)
            Pear               = $PSStyle.BackGround.FromRgb(209, 226, 49)
            AndroidGreen       = $PSStyle.BackGround.FromRgb(164, 198, 57)
            AppleGreen         = $PSStyle.BackGround.FromRgb(141, 182, 0)
            BattleshipGrey     = $PSStyle.BackGround.FromRgb(132, 132, 130)
            Olive              = $PSStyle.BackGround.FromRgb(128, 128, 0)
            ArmyGreen          = $PSStyle.BackGround.FromRgb(75, 83, 32)
            Inchworm           = $PSStyle.BackGround.FromRgb(178, 236, 93)
            LawnGreen          = $PSStyle.BackGround.FromRgb(124, 252, 0)
            BrightGreen        = $PSStyle.BackGround.FromRgb(102, 255, 0)
            Celadon            = $PSStyle.BackGround.FromRgb(172, 225, 175)
            PastelGreen        = $PSStyle.BackGround.FromRgb(119, 221, 119)
            Pistachio          = $PSStyle.BackGround.FromRgb(147, 197, 114)
            DollarBill         = $PSStyle.BackGround.FromRgb(133, 187, 101)
            Asparagus          = $PSStyle.BackGround.FromRgb(135, 169, 107)
            DarkPastelGreen    = $PSStyle.BackGround.FromRgb(3, 192, 60)
            CamouflageGreen    = $PSStyle.BackGround.FromRgb(120, 134, 107)
            IndiaGreen         = $PSStyle.BackGround.FromRgb(19, 136, 8)
            Green              = $PSStyle.BackGround.FromRgb(0, 128, 0)
            DarkOliveGreen     = $PSStyle.BackGround.FromRgb(85, 107, 47)
            RifleGreen         = $PSStyle.BackGround.FromRgb(65, 72, 51)
            Aquamarine         = $PSStyle.BackGround.FromRgb(127, 255, 212)
            Clover             = $PSStyle.BackGround.FromRgb(0, 255, 111)
            AshGrey            = $PSStyle.BackGround.FromRgb(178, 190, 181)
            CambridgeBlue      = $PSStyle.BackGround.FromRgb(163, 193, 173)
            CaribbeanGreen     = $PSStyle.BackGround.FromRgb(0, 204, 153)
            Emerald            = $PSStyle.BackGround.FromRgb(80, 200, 120)
            Mint               = $PSStyle.BackGround.FromRgb(62, 180, 137)
            Jade               = $PSStyle.BackGround.FromRgb(0, 168, 107)
            Xanadu             = $PSStyle.BackGround.FromRgb(115, 134, 120)
            TropicalRainForest = $PSStyle.BackGround.FromRgb(0, 117, 94)
            DarkSpringGreen    = $PSStyle.BackGround.FromRgb(23, 114, 69)
            CadmiumGreen       = $PSStyle.BackGround.FromRgb(0, 107, 60)
            ForestGreen        = $PSStyle.BackGround.FromRgb(1, 68, 33)
            BritishRacingGreen = $PSStyle.BackGround.FromRgb(0, 66, 37)
            DarkGreen          = $PSStyle.BackGround.FromRgb(1, 50, 32)
            DarkJungleGreen    = $PSStyle.BackGround.FromRgb(26, 36, 33)
        }

        Cyan   = [ordered] @{
            Bubbles         = $PSStyle.BackGround.FromRgb(231, 254, 255)
            Cyan            = $PSStyle.BackGround.FromRgb(0, 255, 255)
            ColumbiaBlue    = $PSStyle.BackGround.FromRgb(155, 221, 255)
            BrightTurquoise = $PSStyle.BackGround.FromRgb(8, 232, 222)
            BabyBlue        = $PSStyle.BackGround.FromRgb(137, 207, 240)
            SkyBlue         = $PSStyle.BackGround.FromRgb(135, 206, 235)
            PastelBlue      = $PSStyle.BackGround.FromRgb(174, 198, 207)
            Turquoise       = $PSStyle.BackGround.FromRgb(48, 213, 200)
            DarkCyan        = $PSStyle.BackGround.FromRgb(0, 139, 139)
            Cerulean        = $PSStyle.BackGround.FromRgb(0, 123, 167)
            Teal            = $PSStyle.BackGround.FromRgb(0, 128, 128)
            PineGreen       = $PSStyle.BackGround.FromRgb(1, 121, 111)
            DarkSlateGray   = $PSStyle.BackGround.FromRgb(47, 79, 79)
        }

        Blue   = [ordered] @{
            AliceBlue              = $PSStyle.BackGround.FromRgb(240, 248, 255)
            BabyBlueEyes           = $PSStyle.BackGround.FromRgb(161, 202, 241)
            CarolinaBlue           = $PSStyle.BackGround.FromRgb(153, 186, 221)
            Iceberg                = $PSStyle.BackGround.FromRgb(113, 166, 210)
            CornflowerBlue         = $PSStyle.BackGround.FromRgb(100, 149, 237)
            DarkPastelBlue         = $PSStyle.BackGround.FromRgb(119, 158, 203)
            UnitedNationsBlue      = $PSStyle.BackGround.FromRgb(91, 146, 229)
            BleuDeFrance           = $PSStyle.BackGround.FromRgb(49, 140, 231)
            Azure                  = $PSStyle.BackGround.FromRgb(0, 127, 255)
            AirForceBlue           = $PSStyle.BackGround.FromRgb(93, 138, 168)
            Glaucous               = $PSStyle.BackGround.FromRgb(96, 130, 182)
            SteelBlue              = $PSStyle.BackGround.FromRgb(70, 130, 180)
            Denim                  = $PSStyle.BackGround.FromRgb(21, 96, 189)
            Cadet                  = $PSStyle.BackGround.FromRgb(83, 104, 120)
            Cobalt                 = $PSStyle.BackGround.FromRgb(0, 71, 171)
            YaleBlue               = $PSStyle.BackGround.FromRgb(15, 77, 146)
            DarkCerulean           = $PSStyle.BackGround.FromRgb(8, 69, 126)
            Charcoal               = $PSStyle.BackGround.FromRgb(54, 69, 79)
            Arsenic                = $PSStyle.BackGround.FromRgb(59, 68, 75)
            DarkMidnightBlue       = $PSStyle.BackGround.FromRgb(0, 51, 102)
            CoolBlack              = $PSStyle.BackGround.FromRgb(0, 46, 99)
            OxfordBlue             = $PSStyle.BackGround.FromRgb(0, 33, 71)
            GhostWhite             = $PSStyle.BackGround.FromRgb(248, 248, 255)
            LavenderBlue           = $PSStyle.BackGround.FromRgb(204, 204, 255)
            LavenderGray           = $PSStyle.BackGround.FromRgb(196, 195, 208)
            Ceil                   = $PSStyle.BackGround.FromRgb(146, 161, 207)
            CoolGrey               = $PSStyle.BackGround.FromRgb(140, 146, 172)
            Blue                   = $PSStyle.BackGround.FromRgb(0, 0, 255)
            CeruleanBlue           = $PSStyle.BackGround.FromRgb(42, 82, 190)
            InternationalKleinBlue = $PSStyle.BackGround.FromRgb(0, 47, 167)
            DarkPowderBlue         = $PSStyle.BackGround.FromRgb(0, 51, 153)
            DukeBlue               = $PSStyle.BackGround.FromRgb(0, 0, 156)
            Ultramarine            = $PSStyle.BackGround.FromRgb(18, 10, 143)
            DarkBlue               = $PSStyle.BackGround.FromRgb(0, 0, 139)
            NavyBlue               = $PSStyle.BackGround.FromRgb(0, 0, 128)
            MidnightBlue           = $PSStyle.BackGround.FromRgb(25, 25, 112)
            Sapphire               = $PSStyle.BackGround.FromRgb(8, 37, 103)
            RoyalBlue              = $PSStyle.BackGround.FromRgb(0, 35, 102)
        }

        Purple = [ordered] @{
            BrightLavender   = $PSStyle.BackGround.FromRgb(191, 148, 228)
            Lavender         = $PSStyle.BackGround.FromRgb(181, 126, 220)
            DarkPastelPurple = $PSStyle.BackGround.FromRgb(150, 111, 214)
            Violet           = $PSStyle.BackGround.FromRgb(143, 0, 255)
            DarkLavender     = $PSStyle.BackGround.FromRgb(115, 79, 150)
            PurpleHeart      = $PSStyle.BackGround.FromRgb(105, 53, 156)
            BrightUbe        = $PSStyle.BackGround.FromRgb(209, 159, 232)
            Magenta          = $PSStyle.BackGround.FromRgb(255, 0, 255)
            PastelViolet     = $PSStyle.BackGround.FromRgb(203, 153, 201)
            PastelPurple     = $PSStyle.BackGround.FromRgb(179, 158, 181)
            Byzantine        = $PSStyle.BackGround.FromRgb(189, 51, 164)
            DarkViolet       = $PSStyle.BackGround.FromRgb(148, 0, 211)
            Plum             = $PSStyle.BackGround.FromRgb(142, 69, 133)
            DarkMagenta      = $PSStyle.BackGround.FromRgb(139, 0, 139)
            Byzantium        = $PSStyle.BackGround.FromRgb(112, 41, 99)
            DarkByzantium    = $PSStyle.BackGround.FromRgb(93, 57, 84)
        }
    }
}

function Test-PS7Colors {
    Param(
        [string] $Set = ''
    )
    if ($Set -eq '') {
        $subset = $bsStyle.BackGround.Keys
    }
    else {
        $subset = $bsStyle.BackGround.Keys | Where-Object { $_ -eq $Set }
    }

    $foreground = ($bsStyle.ForeGround['White', 'Black'].Values)
    $subset | ForEach-Object {
        Write-Host "$($PSStyle.ForeGround.BrightWhite)** $_ **$($PSStyle.Reset)"
        [string] $Set = $_
        $bsStyle.BackGround[$_].Keys | ForEach-Object { 
            [string] $Title = $_.PadRight('InternationalKleinBlue'.Length)
            Write-Host "$($PSStyle.ForeGround.White)$Title $($PSStyle.Reset)" -NoNewline
            Write-Host ": " -NoNewline
            $background = $_
            $foreground | ForEach-Object {
                Write-Host "$($bsStyle.BackGround.$Set[$background]+$_) yXy $($PSStyle.Reset)" -NoNewline
            }
            Write-Host "$($PSStyle.Reset)"
        }
        Write-Host "$($PSStyle.Reset)"
    }
}